#!/usr/bin/env bash
#displays the content of the file /etc/passwd, using the while loop + IFS.
while IFS=':' read -r -f1,2,3,4,5,6,7
do
echo The user "$f1" is part of the "$f4" gang, lives in "$f6" and rides "$f7". "$f3"s place is protected by the passcode "$f2", more info about the user here: "$f5"
done
