#!/usr/bin/env bash
#displays the content of the file /etc/passwd, using the while loop + IFS.
FILENAME="/etc/passwd"
while IFS=: read -r f1, f2, f3, f4, f5, f6, f7
do
  echo "$f1, $f2, $f3, $f4, $f5, $f6, $f7"
done < $FILENAME
