#!/usr/bin/env bash
#Write a Bash script that loops from 1 to 10 and: displays bad luck for the 4th loop iteration, displays good luck for the 8th loop iteration.
i=10
while [ $i -gt 0 ]
do
	echo 'Best School'
	((i--))
if [ $i -eq 6 ]
then 
echo 'good luck'
elif [ $i -eq 2 ]
then
echo 'bad luck'
else [ $i -eq 0 ]
break
fi
done
