#!/usr/bin/env bash
#displays numbers from 1 to 20
i=$(($i+1))
while [ $i -le 20 ]
do
	echo $i
case $i in 
	"5") echo 'bad luck from China'
	;;
	"10") echo 'bad luck from Japan'
	;;
	"18") echo 'bad luck from Italy'
	;;
esac
done
