#!/usr/bin/env bash
#displays numbers from 1 to 20
i=1
while [ $i -le 20 ]
do
	echo $i
	i=$(($i+1))
case $i in 
	"4") echo 'bad luck from China'
	;;
	"9") echo 'bad luck from Japan'
	;;
	"17") echo 'bad luck from Italy'
	;;
esac
done
