#!/usr/bin/env bash
#displays the time for 12 hours and 59 minutes.
i=1
while [ $i -lt 59 ]
do
	echo $i
	i=$((i+1))
done
echo 'Hour: 1'
j=1
while [ $j -lt 59 ]
do
        echo $j
        j=$((j+1))
done 
