#!/usr/bin/env bash
#displays the time for 12 hours and 59 minutes.
i=1
j=1
while [ $i -lt 60 ]
do
	echo $i
	i=$((i+1))
	if [ $i -gt 59 ]
	then
		while [ $j -le 12 ] 
		do
		echo 'Hora:' $j
		j=$((j+1))
		echo $i
		done
	fi
done
		
