#!/usr/bin/env bash
#displays the time for 12 hours and 59 minutes.
i=1
j=1
while [ $i -lt 59 ]
	do
		echo $i
		i=$((i+1))
	if [ $i -eq 60 ]
	then
		while [ $j -lt 12 ]
		do
			echo 'Hour:' $j
			j=$((j+1))
			return $i
		done
	fi
done
		
