#!/usr/bin/env bash
#Write a Bash script that displays: The content of the current directory In a list format Where only the part of the name after the first dash is displayed
Write a Bash script that displays:
List="$(ls)"
for f in $List; 
do
	find ./ -type "$f" | rev | cut -d '/' -f1,2 | rev  
done 
