#!/usr/bin/env bash
#Write a Bash script that displays: The content of the current directory In a list format Where only the part of the name after the first dash is displayed
Write a Bash script that displays:
List="$(ls)"
for n in $List; 
do
	printf '%s\n' "$n" | cut -c 3- 	  
done 
