#!/usr/bin/env bash
#Write a Bash script that displays: The content of the current directory In a list format Where only the part of the name after the first dash is displayed
List="$(ls)"
for n in $List; 
do
	printf '%s\n' "$n" | cut -d "-" -f1
done 
