#!/usr/bin/env bash
#that gives you information about the school file.
i=school
if [ -e "$i2" ]
then
	echo 'school file exists'
	if [ -z "$i" ]
        then
                echo 'school file is empty'
        else
                echo 'school file is not empty'
        fi
        if [ -f "$i" ]
        then
                echo 'school is a regular file'
        fi

else
	echo 'school file does not exist'
fi
