#!/usr/bin/env bash
#that gives you information about the school file.
if [ -e $school ]
then
	echo 'school file does not exist'
else
	echo 'school file exists'
fi
if [ -z $school ]
then
        echo 'school file is not empty'
else 
	echo 'school file is empty'
fi
if [ -f $school ]
then
	echo ''
else
	echo 'school is a regular file'
fi
