#!/usr/bin/env bash
#that gives you information about the school file.
if [ school -e ]
then
	echo 'school file exists'
else
	echo 'school file does not exist'
fi
if [ school -s ]
then
        echo 'school file is empty'
else 
	echo 'school file is not empty'
fi
if [ school -f ]
then
	echo 'school is a regular file'
fi
