#!/usr/bin/env bash
#Process and PID file
echo $$ > /var/run/holbertonscript.pid

trap "$(echo 'Y U no love me?!')"; exit 1; rm /var/run/holbertonscript.pid SIGINT
trap "$(echo 'I hate the kill command')"; exit 1; rm /var/run/holbertonscript.pid SIGTERM

while :; do
	echo To infinity and beyond
	sleep 2
done
