#!/usr/bin/env bash
# displays: To infinity and beyond indefinitely With a sleep 2 in between each iteratio I am invincible!!! when receiving a SIGTERM signal 
trap 'echo "I am invincible!!!"' SIGTERM
i=0
while [ $i ]; do
	echo 'To infinity and beyond'
	sleep 2
done
